### ISSUE TITLE
Exceptions thrown from related model being represented as coming from the relationship property itself.

### ISSUE THREAD

**Issue by wolverdude** [klen/mixer#38]
I came across an error when using Mixer, but the stack trace sent me in the wrong direction at first. The trace indicated there was a problem processing a SQLAlchemy relationship definition. I eventually discovered that the error wasn't on the relationship itself, but one of the columns in the related table was creating issues. The misdirection in this stack trace made it very difficult to debug.

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/mixer/main.py", line 576, in blend
        return type_mixer.blend(**values)
      File "/usr/local/lib/python2.7/site-packages/mixer/main.py", line 125, in blend
        for name, value in defaults.items()
      File "/usr/local/lib/python2.7/site-packages/mixer/main.py", line 125, in <genexpr>
        for name, value in defaults.items()
      File "/usr/local/lib/python2.7/site-packages/mixer/mix_types.py", line 220, in gen_value
        return type_mixer.gen_field(field)
      File "/usr/local/lib/python2.7/site-packages/mixer/main.py", line 202, in gen_field
        return self.gen_value(field.name, field, unique=unique)
      File "/usr/local/lib/python2.7/site-packages/mixer/main.py", line 255, in gen_value
        field_name, self.__scheme.__name__, exc))
    ValueError: Mixer (myproject.models.Order): Generation for customer (Order) has been stopped. Exception: 'NoneType' object has no attribute '__bases__'

That last line should read something like this, with perhaps a reference that it was coming from `myproject.models.Order`:

    ValueError: Mixer (myproject.models.Customer): Generation for time_created (Customer) has been stopped. Exception: 'NoneType' object has no attribute '__bases__'

**Comment by klen** [comment]
Latests versions of the Mixer should provide more informations.

**Comment by jasonrhaas** [comment]
I'm running into this as well.  Running `mixer==5.6.6`
