### ISSUE TITLE
Mixer for my flask app gives error when used with db.init_app() -- AttributeError: 'module' object has no attribute 'extensions'

### ISSUE THREAD

**Issue by hussaintamboli** [klen/mixer#41]
Hi,

I am trying to use `mixer` with my flask app to create fake data. I have written below mixer module 

    # module: my-mixer.py
    from flask import Flask
    from mixer.backend.flask import mixer
    from faker import Faker

    from database import db
    from models import Country
    from recruitment import app

    app = flask.Flask('myapp')
    db.init_app(app)
    db.app = app

    fake = Faker()

    mixer.init_app(app)

    # Generate a random country
    country = mixer.blend(Country)

    # Generate a Country. Set country name.
    country = mixer.blend(Country, country__name=fake.country())
    
The db is taken from 

    from flask.ext.sqlalchemy import SQLAlchemy
    # no app object passed! Instead we use use db.init_app in the factory.
    db = SQLAlchemy()

You can see that I am not directly binding app with db

    db = SQLAlchemy(app)

Now when I run **my-mixer.py**, I get below error

    Traceback (most recent call last):
    File "faker-mixer.py", line 16, in <module>
    mixer.init_app(app)
    File "/home/hussain/workspace/magic-chips/backend/venv/local/lib/python2.7/site-packages/mixer/backend/flask.py", line 45, in init_app
    assert app.extensions and app.extensions[
    AttributeError: 'module' object has no attribute 'extensions'

**Comment by hussaintamboli** [comment]
I also tried the `Mixer` class from `mixer.backend.flask`

    from mixer.backend.flask import Mixer
    mixer = Mixer(app, commit=True) 

It gives me a new error

    AttributeError: Mixer (<class 'models.Country'>): 'NoneType' object has no attribute '__bases__'

**Comment by rmrio** [comment]
Hi hussaintamboli
Did you resolve the issue?

**Comment by hussaintamboli** [comment]
I end up using just Faker instead. I'll try to reproduce this issue when I get time.

**Comment by Mappboy** [comment]
Just a head's up I had a similar issue. The first error:
> AttributeError: 'module' object has no attribute 'extensions'
In my case was because I was testing with out setting the application context. 
```
with app.app_context():
    country = mixer.blend(Country)
```
The second issue:
> AttributeError: Mixer (<class 'models.Country'>): 'NoneType' object has no attribute '__bases__'.
Is most likely because the Country model contains a field not in the standard Sqlalchemy GenFactory. In my case (missing postgresql dialects UUID and ARRAY) this was resolved by creating a new factory for the missing fields.
```
def get_extents_array():
    """
    Generate a random extents array
    """
    return [0,1,0,1]

class SeerFactory(GenFactory):
    generators = {
        UUID: uuid4().__str__,
        (db.ARRAY, ARRAY): get_extents_array
    }
mixer = Mixer(commit=True, factory=SeerFactory)
```
This could be potentially made more clear in the GenFactory(mixer/ factory.py) classmethod get_fabric. If the field type doesn't exist fcls will equal None and therefore will not have a __bases__ attribute. I'm not knowledgable enough about the code base to suggest a fix for it. But it should probably be a little more verbose about what field it doesn't have in the factory. I guess it's maybe worthwhile having and assert fcls is not None. 

Offending piece of code at line 172 of factory.py. 
```
# this will not work if fcls is None
if not func and fcls.__bases__:
    func = cls.generators.get(fcls.__bases__[0])
```
I hope that helps.

**Comment by Mappboy** [comment]
I think this is similar issue to the fix in pull request #80
