### ISSUE TITLE
sqlalchemy_utils ChoiceType nullable failure

### ISSUE THREAD

**Issue by maplye** [klen/mixer#47]
I defined a column as sqlalchemy_utils ChoiceType

    class JzPlan(db.Model):
        CREATED = u'CREATED'
        ASSIGNED = u'ASSIGNED'
        CHECKED = u'CHECKED'
        PLAN_STATUS = [
        (CREATED, u'A'),
        (ASSIGNED, u'B'),
        (CHECKED, u'C'),
       ]
        id = db.Column(db.Integer(), primary_key=True)
        ddbh = db.Column(db.String(50), nullable=False)
        xqf = db.Column(db.String(50), nullable=False)
        xmpc = db.Column(db.String(50), nullable=False)
        jslx = db.Column(db.String(50), nullable=False)
        ds = db.Column(db.String(50), nullable=False)
        qx = db.Column(db.String(50), nullable=False)
        zm = db.Column(db.String(50), nullable=False)
        xxdz = db.Column(db.String(50), nullable=False)
        fgcj = db.Column(db.String(50), nullable=False)
        ysjfsj = db.Column(db.DateTime, nullable=False)
        qyjl_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
        qyjl = db.relation(User, innerjoin=True, lazy="joined")
        status = db.Column(ChoiceType(PLAN_STATUS))
        enabled = db.Column(db.Boolean, default=True, nullable=False)

then I set the mixer as below, that's OK:

    plan = mixer.blend(JzPlan)

but I set the status nullable attribute, the failure raised.

    status = db.Column(ChoiceType(PLAN_STATUS), nullable=False)

The error message as below:

    ---------------------------- Captured stderr call -----------------------------
    Traceback (most recent call last):
      File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line 577, in blend
    return type_mixer.blend(**values)
      File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line125, in blend for name, value in defaults.items()
      File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line125, in <genexpr>
    for name, value in defaults.items()
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\mix_types.py",line 220, in gen_value
    return type_mixer.gen_field(field)
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line202, in gen_field
    return self.gen_value(field.name, field, unique=unique)
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line245, in gen_value
    fab = self.get_fabric(field, field_name, fake=fake)
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line291, in get_fabric
    self.__fabrics[key] = self.make_fabric(field.scheme, field_name, fake)
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\backend\sqlalchemy.py", line 181, in make_fabric
    stype, field_name=field_name, fake=fake, kwargs=kwargs)
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\main.py", line307, in make_fabric
    fab = self.__factory.get_fabric(scheme, field_name, fake)
    File "D:\Develop\Python\env\towerprice\lib\site-packages\mixer\factory.py", line 159, in get_fabric
    if not func and fcls.__bases__:
    AttributeError: Mixer (<class 'towerprice.models.JzPlan'>): 'NoneType' object has no attribute '__bases__'

**Comment by eelkeh** [comment]
I think #58 might fix this.
